### ISSUE TITLE
注文手続き画面でお届け先を変更できない

### ISSUE THREAD

**Issue by Hayato07** [kurozumi/Stripe4#19]
お届け先の変更、またはお届け先の追加を選択すると、注文手続き画面をリロードする結果となる。

## 発生条件

EC-CUBEインストール後にREADME.mdの手順でプラグインを設定した状態。

ゲスト、会員ともに発生

## 原因
下記のエラー処理まで進んでしまっている。

Stripe4/Form/Extension/CreditCardExtension.php

```
if (null === $order->getStripePaymentMethodId()) {
    $form->get('stripe_payment_method_id')->addError(new FormError(trans('エラーが発生しました')));
}
```

## 対応方法

POSTにredirect_toを持っているかどうかでチェックはできますが、あまり良い解決方法ではないのかなと思っています。

**Comment by kurozumi** [comment]
@Hayato07 

ありがとうございます！

修正してみましたがこちらでいかがでしょうか？
注文内容確認時にStripeの支払い方法IDが受注データに保存されているかチェックする必要があるので、
redirect_toを持っているかどうかチェックすることにしました。

https://github.com/kurozumi/Stripe4/pull/20

**Comment by Hayato07** [comment]
コード見ました。問題ないと思います。

**Comment by kurozumi** [comment]
@Hayato07 

マージしたのでクローズします。
